SET PATH=C:\Keil_v5\ARM\ARMCC\Bin;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files (x86)\Nordic Semiconductor\nrf5x\bin\;C:\Program Files\PuTTY\;C:\Program Files\Git\cmd;C:\Windows\system32\config\systemprofile\.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm\;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;D:\opencv\opencv\build\x64\vc15\bin;F:\aaa\Shared\LabVIEW CLI;;D:\AAA\Microsoft VS Code\bin
SET CPU_TYPE=STM32F411CEUx
SET CPU_VENDOR=STMicroelectronics
SET UV2_TARGET=KDWM1000
SET CPU_CLOCK=0x007A1200
"C:\Keil_v5\ARM\ARMCC\Bin\ArmCC" --Via ".\obj\main.__i"
"C:\Keil_v5\ARM\ARMCC\Bin\ArmCC" --Via ".\obj\ranging.__i"
"C:\Keil_v5\ARM\ARMCC\Bin\ArmCC" --Via ".\obj\stdplus_queue.__i"
"C:\Keil_v5\ARM\ARMCC\Bin\ArmAsm" --Via ".\obj\startup_stm32f411xe._ia"
"C:\Keil_v5\ARM\ARMCC\Bin\ArmCC" --Via ".\obj\system_stm32f4xx.__i"
"C:\Keil_v5\ARM\ARMCC\Bin\ArmCC" --Via ".\obj\misc.__i"
"C:\Keil_v5\ARM\ARMCC\Bin\ArmCC" --Via ".\obj\stm32f4xx_rcc.__i"
"C:\Keil_v5\ARM\ARMCC\Bin\ArmCC" --Via ".\obj\stm32f4xx_syscfg.__i"
"C:\Keil_v5\ARM\ARMCC\Bin\ArmCC" --Via ".\obj\stm32f4xx_exti.__i"
"C:\Keil_v5\ARM\ARMCC\Bin\ArmCC" --Via ".\obj\stm32f4xx_gpio.__i"
"C:\Keil_v5\ARM\ARMCC\Bin\ArmCC" --Via ".\obj\stm32f4xx_usart.__i"
"C:\Keil_v5\ARM\ARMCC\Bin\ArmCC" --Via ".\obj\stm32f4xx_spi.__i"
"C:\Keil_v5\ARM\ARMCC\Bin\ArmCC" --Via ".\obj\stm32f4_delay.__i"
"C:\Keil_v5\ARM\ARMCC\Bin\ArmCC" --Via ".\obj\stm32f4_usart.__i"
"C:\Keil_v5\ARM\ARMCC\Bin\ArmCC" --Via ".\obj\stm32f4_spi.__i"
"C:\Keil_v5\ARM\ARMCC\Bin\ArmCC" --Via ".\obj\serial.__i"
"C:\Keil_v5\ARM\ARMCC\Bin\ArmCC" --Via ".\obj\dw1000.__i"
"C:\Keil_v5\ARM\ARMCC\Bin\ArmCC" --Via ".\obj\string.__i"
"C:\Keil_v5\ARM\ARMCC\Bin\ArmCC" --Via ".\obj\deca_device.__i"
"C:\Keil_v5\ARM\ARMCC\Bin\ArmCC" --Via ".\obj\deca_params.__i"
"C:\Keil_v5\ARM\ARMCC\Bin\ArmCC" --Via ".\obj\kdwm1000_bsp.__i"
"C:\Keil_v5\ARM\ARMCC\Bin\ArmCC" --Via ".\obj\kdwm1000_it.__i"
"C:\Keil_v5\ARM\ARMCC\Bin\ArmLink" --Via ".\Obj\STM32F411C.lnp"
